name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker login
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      
    - name: Docker pull
      run: docker pull docker.pkg.github.com/wadus16/jenkins/test:1.0
      
    - name: Docker images
      run: docker images
      
    - name: Docker pull
      run: docker pull docker.pkg.github.com/wadus16/jenkins/test:1.0
      
    - name: Docker run
      run: docker run --rm docker.pkg.github.com/wadus16/jenkins/test:1.0 /bin/bash
      
    - name: Docker hello
      run: echo "hello!"
    
